### ISSUE TITLE
Hassio not a directory

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-folder-sensor#1]
On Hassio, the following config:
```
homeassistant:
.
.
.
  whitelist_external_dirs:
    - /share

sensor:
  - platform: folder
    folder_paths:
      - /share/motion
      - /config
```

Gives error:
```
Invalid config for [homeassistant]: not a directory @ data['whitelist_external_dirs'][0]. Got '/share/motion/'. 
```
